### ISSUE TITLE
Create api route for posting user articles: flask

### ISSUE THREAD

**Issue by sauravshah31** [sauravshah31/SoulSion#2]
Define API route for posting articles of user ```/api/articles/post```.
The declaration for this route already defined in: ```back-end/src/soulsion_api/articles/routes.py```
Complete the function ```post_article``` and update the doc ```/back-end/docs/articles_api.md``` for the corresponding route.

**Comment by sahil-ramagiri** [comment]
can I work on this?

**Comment by sauravshah31** [comment]
Yes you can. First complete the get_random_file_name function in utils/utils.py, than use that function to get a random file name. Also make sure that the file name doesn't exists in the database, if it does, call the function again. Don't use any models in utils.py.
