### ISSUE TITLE
chat box doesn't scroll after fetching data

### ISSUE THREAD

**Issue by sauravshah31** [sauravshah31/SoulSion#3]
to duplicate this issue:
* go to soulsion.com/chat
* type 'what is stress' in the chat box, and send the message
* Notice that the chat box doesn't scroll down all the way down (only upto the message not the link)

This should be fixed by using the ```document.scrollBy``` after appending the link to the scroll in ```/front-end/src/components/chat/chat-box.js```

**Comment by dheerajd5** [comment]
Can you assign me this issue?

**Comment by dheerajd5** [comment]
I have a doubt, in line 235, we already append the link to the synchroniser chat box, in this line - "lastTextElement.appendChild(link);" so it should be enough to just change the scrollTo method to scrollBy method, but it's said you need to append the link first.

**Comment by dheerajd5** [comment]
I have a doubt, in line 235, we already append the link to the synchroniser chat box, in this line - _"lastTextElement.appendChild(link);"_ so it should be enough to just change the **scrollTo** method to **scrollBy** method, but it's said you need to append the link first.

**Comment by sauravshah31** [comment]
> I have a doubt, in line 235, we already append the link to the synchroniser chat box, in this line - _"lastTextElement.appendChild(link);"_ so it should be enough to just change the **scrollTo** method to **scrollBy** method, but it's said you need to append the link first.

No, the issue is caused because of asynchronous nature of fetching the reply. So, if you use scrollBy, the displayChat is called first, and the scoll will still not go all the way down. Also prefer using scrollTo as scrollBy has some undefined behaviour in some of the browsers.

`Hint:` have a look at `display_chat` function. You just have to copy one line from this, and paste it after appending the source.

**Comment by sauravshah31** [comment]
> ### EDIT:
> After reading the code a bit more and googling,
> I think in this code snippet, we have to give **source** also with **reply** to the **displayChatRecieved** method right?
> _const reply = bestReply.snippet; const source = bestReply.link; displayChatReceived(reply);_

display_chat is a generic function for displaying message from both user and computer, so if you do so, you might have to do some checking. There is a better way to achieve this.

**Comment by dheerajd5** [comment]
> > ### EDIT:
> > After reading the code a bit more and googling,
> > I think in this code snippet, we have to give **source** also with **reply** to the **displayChatRecieved** method right?
> > _const reply = bestReply.snippet; const source = bestReply.link; displayChatReceived(reply);_
> 
> display_chat is a generic function for displaying message from both user and computer, so if you do so, you might have to do some checking. There is a better way to achieve this.

Okay, So I think we just have to add this line _synchronizer_chat.chatBox.scrollTo(0,synchronizer_chat.chatBox.scrollHeight);_
after we append the link _"lastTextElement.appendChild(link);" _

Is this correct?

**Comment by sauravshah31** [comment]
> 
> 
> > > ### EDIT:
> > > After reading the code a bit more and googling,
> > > I think in this code snippet, we have to give **source** also with **reply** to the **displayChatRecieved** method right?
> > > _const reply = bestReply.snippet; const source = bestReply.link; displayChatReceived(reply);_
> > 
> > 
> > display_chat is a generic function for displaying message from both user and computer, so if you do so, you might have to do some checking. There is a better way to achieve this.
> 
> Okay, So I think we just have to add this line _synchronizer_chat.chatBox.scrollTo(0,synchronizer_chat.chatBox.scrollHeight);_
> after we append the link _"lastTextElement.appendChild(link);"_
> 
> Is this correct?

Yup. But do a through test before sending a PR, just in case.

**Comment by dheerajd5** [comment]
> > > > ### EDIT:
> > > > After reading the code a bit more and googling,
> > > > I think in this code snippet, we have to give **source** also with **reply** to the **displayChatRecieved** method right?
> > > > _const reply = bestReply.snippet; const source = bestReply.link; displayChatReceived(reply);_
> > > 
> > > 
> > > display_chat is a generic function for displaying message from both user and computer, so if you do so, you might have to do some checking. There is a better way to achieve this.
> > 
> > 
> > Okay, So I think we just have to add this line _synchronizer_chat.chatBox.scrollTo(0,synchronizer_chat.chatBox.scrollHeight);_
> > after we append the link _"lastTextElement.appendChild(link);"_
> > Is this correct?
> 
> Yup. But do a through test before sending a PR, just in case.

Okay thanks for the help 👍

**Comment by dheerajd5** [comment]
I have run into a problem, when i run the site on local host and click on chat box, it doesn't open up like the main site, but I compared the urls of the two, and found out when I add "?route=chat" to the localhost url, the chat box pops up just like in the main site. Why does this happen, did I do something wrong in the cloning or setting up of the repo?

**Comment by sauravshah31** [comment]
> 
> 
> I have run into a problem, when i run the site on local host and click on chat box, it doesn't open up like the main site, but I compared the urls of the two, and found out when I add **?route=chat** to the localhost url, the chat box pops up just like in the main site. Why does this happen, did I do something wrong in the cloning or setting up of the repo?

No, you didn't do anything wrong. There was a problem in deploying React app (react-router-dom) in gh-pages , so I had to write the logic this way. Don't worry!!

**Comment by sauravshah31** [comment]
resolved
