### ISSUE TITLE
url to the source is invalid

### ISSUE THREAD

**Issue by sauravshah31** [sauravshah31/SoulSion#4]
to duplicate this issue:
* go to soulsion.com/chat
* type 'what is stress' in the chat box, and send the message
* click the source link
* Notice that the link is not valid (You might need to send the message more than 1 time before you get an invalid link)

Refer to the code in ```/front-end/src/components/chat/chat-box.js```. This is probably caused because the ```source``` is the ```formattedUrl``` link instead of the original link. Refer to the google custom search engine api doc, and replace the ```formattedUrl``` accordingly.

**Comment by dheerajd5** [comment]
I'm trying to resolving this issue.

**Comment by sauravshah31** [comment]
resolved
