### ISSUE TITLE
white vertical bar on the home page

### ISSUE THREAD

**Issue by sauravshah31** [sauravshah31/SoulSion#6]
Go to soulsion.com
Notice that there is a vertical white bar on the left side of the quote.

Can you fix this? Have a look at the code at ```front-end/src/components/homepage/homepage-top-header.js```, class ```Quote```.
I think this is some bootstrap issue.

**Comment by av1shek** [comment]
I would like to solve this issue, please assign me

**Comment by sauravshah31** [comment]
resolved, blockquote issue
